In [2]:
import numpy as np

In [3]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])

In [4]:
a+b

array([15, 23, 14,  8])

In [5]:
a-b

array([ 5, -7, -4, -6])

In [6]:
a = np.array([120, 45, 68])
omega = 0.2
c = a * omega
c

array([24. ,  9. , 13.6])

In [8]:
x = np.array([5, 2])
y = np.array([-5, -11])

In [9]:
x+y

array([ 0, -9])

In [10]:
x-y

array([10, 13])

In [12]:
a = np.array([120, 150, 190])
b = np.array([130, 130, 130])
c = np.array([2, 3, 2.5])
omega = 72

In [15]:
d = c*omega
d

array([144., 216., 180.])

In [16]:
a+b+d

array([394., 496., 500.])

In [17]:
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])
omega1 = 500
omega2 = 100
omega3 = 0
u = omega1*p + omega2*v + omega3*s
u

array([1800, 3000, 2700])

In [18]:
x = np.array([4, 5])
y = np.array([2, 1])
z = np.array([1, 0])
omega1 = 2
omega2 = -3
omega3 = 5
w = omega1*x + omega2*y + omega3*z

In [19]:
w

array([7, 7])

In [24]:
n = np.array([3, 4, 5, 9])
m = np.array([1, 5, 3, 6])
omega1 = 200
omega2 = 400
l = omega2*m - omega1*n
l

array([-200, 1200,  200,  600])

In [25]:
a = np.array([65, 70, 120, 30])
w = np.array([0.4, 0.4, 0.2, 0.8])
np.dot(a, w)

102.0

In [26]:
b = np.array([4,5,-1])
c = np.array([2,0,1])
np.dot(b,c)

7