In [2]:
import pandas as pd
import numpy as np

In [3]:
A = np.array([
    [1, -5, 3], 
    [2, 2, 1],
    [0, 3, 1],
    [2, 4, 12]
])
A

array([[ 1, -5,  3],
       [ 2,  2,  1],
       [ 0,  3,  1],
       [ 2,  4, 12]])

In [4]:
A.shape

(4, 3)

In [5]:
print('a_23=', A[1, 2], 'a_32=', A[2, 1], 'a_33=', A[2,2])

a_23= 1 a_32= 3 a_33= 1


In [1]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Consumption = np.array([50,50,60])
Wife_Consumption = np.array([100,80,140])
Mother_In_Law_Consumption = np.array([100,20,140])

In [44]:
Inc = np.array([Husband_Income, + Wife_Income, + Mother_In_Law_Income])
Cons = np.array([Husband_Consumption, + Wife_Consumption, + Mother_In_Law_Consumption])


In [45]:
Inc

array([[100, 220, 140],
       [150, 200, 130],
       [ 90,  80, 100]])

In [46]:
Cons

array([[ 50,  50,  60],
       [100,  80, 140],
       [100,  20, 140]])

In [47]:
Inc1 = 0.87*Inc
Inc1.T

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

In [48]:
P = Inc1 - Cons

In [49]:
P.T


array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

In [50]:
A = np.matrix("1, -5; 2, 2; 0, 3")
B = np.matrix("3, 1, 0; -1, 0, 2")

In [51]:
A

matrix([[ 1, -5],
        [ 2,  2],
        [ 0,  3]])

In [52]:
B

matrix([[ 3,  1,  0],
        [-1,  0,  2]])

In [53]:
np.dot(A, B)

matrix([[  8,   1, -10],
        [  4,   2,   4],
        [ -3,   0,   6]])

In [54]:
np.dot(B, A)

matrix([[  5, -13],
        [ -1,  11]])

In [55]:
C = np.matrix('1,-1,2,4,0; 8,2,0,5,3; 0,1,2,1,2')
C

matrix([[ 1, -1,  2,  4,  0],
        [ 8,  2,  0,  5,  3],
        [ 0,  1,  2,  1,  2]])

In [56]:
D = np.matrix('1,0,1,0; 0,0,2,-1; 1,0,1,1; 0,1,1,1; 1,1,0,-1')
D

matrix([[ 1,  0,  1,  0],
        [ 0,  0,  2, -1],
        [ 1,  0,  1,  1],
        [ 0,  1,  1,  1],
        [ 1,  1,  0, -1]])

In [57]:
C*D

matrix([[ 3,  4,  5,  7],
        [11,  8, 17,  0],
        [ 4,  3,  5,  0]])

In [4]:
a = np.matrix('2, 0; 0, 2')
b = np.matrix('1, 1; 4, 5')

In [5]:
a*b

matrix([[ 2,  2],
        [ 8, 10]])

In [6]:
b*a

matrix([[ 2,  2],
        [ 8, 10]])

## Задание 6.9

In [16]:
F = np.matrix('1, 2, 1; 1, -1, 2')
F

matrix([[ 1,  2,  1],
        [ 1, -1,  2]])

In [17]:
Ft = F.T
Ft

matrix([[ 1,  1],
        [ 2, -1],
        [ 1,  2]])

In [18]:
G = Ft*F
G

matrix([[2, 1, 3],
        [1, 5, 0],
        [3, 0, 5]])