In [1]:
import numpy as np

In [2]:
# составляем матрицу А 
A = np.array([
    [2, 5, -4],
    [6, 3, 0],
]).T
# применяем сингулярное разложение
np.linalg.svd(A)

(array([[-0.66666667,  0.66666667, -0.33333333],
        [-0.66666667, -0.33333333,  0.66666667],
        [ 0.33333333,  0.66666667,  0.66666667]]),
 array([8.48528137, 4.24264069]),
 array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]))

Функция возвращает кортеж из трёх массивов:

+ Левая матрица сингулярного разложения U, состоящая из собственных векторов матрицы A*A^T.
+ Сингулярные числа, стоящие на главной диагонали матрицы D.
+ Правая матрица сингулярного разложения V^T, состоящая из собственных векторов матрицы A^T*A.

Кстати, заметьте, что наш результат полностью совпал с результатом сингулярного разложения, вычисленным вручную.